<?php $f3 = \Base::instance() ?>

<!-- Foundation 5 header -->
<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" >

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><?php echo $title; ?></title>

  <!-- If you are using CSS version, only link these 2 files, you may add app.css to use for your overrides if you like. -->
  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/foundation.css">
  <link rel="stylesheet" href="css/app.css" />

  <script src="/js/vendor/jquery.js"></script>
  <script src="/js/vendor/fastclick.js"></script>

  <script src="js/vendor/modernizr.js"></script>

</head>
<body>
